language: python
python:
    - "3.4"
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - sed -i "s/pelican-3/pelican/" Makefile
    - git submodule update --init --recursive
install: 
    - pip install -r requirements.txt
script:
    - make html

notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/dca6d04df2dcb14b6f38
        on_success: always
        on_failure: always
        on_start: always
    slack: uhbiocomputation:s6no6nPWj67Y0bntyZzwI9f0
