language: python
python:
    - "2.7"
    - "3.4"
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install: 
    - pip install --user pelican BeautifulSoup4
    - pip3 install --user icalendar pytz
script:
    - make html

notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/dca6d04df2dcb14b6f38
        on_success: always
        on_failure: always
        on_start: always

